# Generated by Django 5.1.2 on 2024-11-08 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medicos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_pacientes', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_citas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('medico_id', models.ForeignKey(db_column='medico_id', on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.medico')),
                ('paciente_id', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamientos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('medico_id', models.ForeignKey(db_column='medico_id', on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.medico')),
                ('paciente_id', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.paciente')),
            ],
        ),
    ]
